CREATE TABLE `person` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `first_name` varchar(255) NOT NULL DEFAULT '',
  `last_name` varchar(255) NOT NULL DEFAULT '',
  `picture_id` int(11) NOT NULL,
  `birthdate` date DEFAULT NULL,
  `death` date DEFAULT NULL,
  `picture_interval_year_start` int(11) DEFAULT NULL,
  `picture_interval_year_end` int(11) DEFAULT NULL,
  `adress_at_time_of_picture` text,
  `fathers_name` varchar(255) DEFAULT NULL,
  `mothers_name` varchar(255) DEFAULT NULL,
  `married_with` varchar(255) DEFAULT NULL,
  `kids` text,
  `notes` text,
  `place_of_birth` text,
  `place_of_death` text,
  `date_of_mariage` date DEFAULT NULL,
  `name_after_birth` varchar(255) DEFAULT NULL,
  `2nd_mariage_partner` varchar(255) DEFAULT NULL,
  `2nd_mariage_date` text,
  `2nd_mariage_place` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=696 DEFAULT CHARSET=utf8;
